CI:add debian build
analogdevicesinc/libad9361-iio pull request #96
Opened 2023-07-28 12:14 UTC by ccraluca

Add debian Bullseye build to Azure CI.

2023-08-09 14:49 UTC, SRaus requested changes

2023-08-09 14:49 UTC, SRaus commented on CI/travis/ci-linux.sh
> +#!/bin/bash
you can split this file in 2 : ci-debian.sh and ci-centos.sh since there already exists ci-ubuntu.sh

2023-08-09 14:49 UTC, SRaus commented on CI/travis/ci-linux.sh
> +	yum -y install bzip2 gzip
yum install -y lines can be merged together.

2023-08-09 14:49 UTC, SRaus commented on CI/travis/ci-linux.sh
> +handle_default() {
this can bee replaced with handle_debian()

2023-08-10 14:26 UTC, tfcollins commented on CI/travis/ci-linux.sh
> +	cd /ci
This probably isn't necessary. The containers will ship with python installed

2023-08-11 09:59 UTC, ccraluca commented on CI/travis/ci-linux.sh
> +#!/bin/bash
I will change the function name from handle_default() to handle_debian(), but I purposely created only one script because it is called for a single job and is split into functions for each OS via the OS_TYPE parameter.

2023-08-11 10:17 UTC, ccraluca commented on CI/travis/ci-linux.sh
> +	cd /ci
I move to this python version for the next CI updates on builds, CentOS, Fedora and openSUSE.
But I will drop it for now since is unrelated to this PR.

2023-08-11 10:21 UTC, ccraluca commented on CI/travis/ci-linux.sh
> +#!/bin/bash
NVM, I found a solution to implement what you said

2023-08-11 10:35 UTC, ccraluca commented
I split the ci-linux.sh script into two parts and the centos part will be added in the next updates since it is not related to this PR.

2023-08-11 10:39 UTC, SRaus approved these changes

2023-08-11 10:58 UTC, merged